
var dataType=[
    {
        type:'搞笑',
        id:'gxmy'
    },{
        type:'字谜',
        id:'zmmy'
    },{
        type:'成语',
        id:'cymy'
    },{
        type:'动物',
        id:'dwmy'
    },{
        type:'爱情',
        id:'aqmy'
    },{
        type:'灯谜',
        id:'dmmy'
    },{
        type:'人名',
        id:'rmmy'
    },{
        type:'地名',
        id:'dimmy'
    },{
        type:'词语',
        id:'cy'
    },{
        type:'带格',
        id:'dgmy'
    },{
        type:'用语',
        id:'yy'
    },{
        type:'儿童',
        id:'etmy'
    },{
        type:'物品',
        id:'wpmy'
    },{
        type:'植物',
        id:'zwmy'
    },{
        type:'谜名',
        id:'jmmy'
    },{
        type:'书报',
        id:'sbmy'
    },{
        type:'故事',
        id:'mygs'
    },{
        type:'俗语',
        id:'symy'
    },{
        type:'药品',
        id:'ypmy'
    },{
        type:'音乐',
        id:'yymy'
    },{
        type:'影视',
        id:'ysmy'
    },{
        type:'称谓',
        id:'cwmy'
    },{
        type:'趣味',
        id:'qtmy'
    },{
        type:'精选',
        id:'miyujingxuan'
    },{
        type:'脑筋急转弯',
        id:'njmy'
    },{
        type:'智力问答',
        id:'zlmy'
    }
]

module.exports = {
    dataType:dataType
};